### ISSUE TITLE
Check running on PR not into master

### ISSUE THREAD

**Issue by leonardt** [Kuree/aha-flow-app#1]
Is it possible to guard the check such that it only runs on PRs into master?

See https://github.com/leonardt/fault/pull/110 for a pull into another branch that is running the check.

**Comment by Kuree** [comment]
Is this still an issue? The code seems to be skipping non-master PR. Maybe there is a typo somewhere.

**Comment by leonardt** [comment]
I haven't encountered it recently, okay to close.  will reopen if I see it again.
